package eg.com.otloblana.service.entity;

// Generated Nov 9, 2015 12:01:04 AM by Hibernate Tools 4.0.0

import eg.com.otloblana.common.entity.GenericEntity;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * GroupEntity generated by hbm2java
 */
@Entity
@Table(name = "group")
public class GroupEntity implements java.io.Serializable,GenericEntity {

	private int id;
	private UserEntity userEntity;
	private String name;
	private String location;
	private Set<MemberEntity> memberEntities = new HashSet<MemberEntity>(0);

	public GroupEntity() {
	}

	public GroupEntity(int id, UserEntity userEntity, String name) {
		this.id = id;
		this.userEntity = userEntity;
		this.name = name;
	}

	public GroupEntity(int id, UserEntity userEntity, String name, String location,
					   Set<MemberEntity> memberEntities) {
		this.id = id;
		this.userEntity = userEntity;
		this.name = name;
		this.location = location;
		this.memberEntities = memberEntities;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "owner_id", nullable = false)
	public UserEntity getUserEntity() {
		return this.userEntity;
	}

	public void setUserEntity(UserEntity userEntity) {
		this.userEntity = userEntity;
	}

	@Column(name = "name", nullable = false, length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "location", length = 200)
	public String getLocation() {
		return this.location;
	}

	public void setLocation(String location) {
		this.location = location;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "groupEntity")
	public Set<MemberEntity> getMemberEntities() {
		return this.memberEntities;
	}

	public void setMemberEntities(Set<MemberEntity> memberEntities) {
		this.memberEntities = memberEntities;
	}

}
