package eg.com.otloblana.service.entity;

// Generated Nov 9, 2015 12:01:04 AM by Hibernate Tools 4.0.0

import eg.com.otloblana.common.entity.GenericEntity;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * StoreEntity generated by hbm2java
 */
@Entity
@Table(name = "store")
public class StoreEntity implements java.io.Serializable,GenericEntity {

	private int id;
	private String name;
	private Set<PriceListEntity> priceListEntities = new HashSet<PriceListEntity>(0);

	public StoreEntity() {
	}

	public StoreEntity(int id, String name) {
		this.id = id;
		this.name = name;
	}

	public StoreEntity(int id, String name, Set<PriceListEntity> priceListEntities) {
		this.id = id;
		this.name = name;
		this.priceListEntities = priceListEntities;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false, length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "storeEntity")
	public Set<PriceListEntity> getPriceListEntities() {
		return this.priceListEntities;
	}

	public void setPriceListEntities(Set<PriceListEntity> priceListEntities) {
		this.priceListEntities = priceListEntities;
	}

}
