package eg.com.otloblana.service.entity;

// Generated Nov 9, 2015 12:01:04 AM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * OrderEntity generated by hbm2java
 */
@Entity
@Table(name = "order")
public class OrderEntity implements java.io.Serializable {

	private int id;
	private UserEntity userEntity;
	private String number;
	private Set<OrderDetailEntity> orderDetailEntities = new HashSet<OrderDetailEntity>(0);

	public OrderEntity() {
	}

	public OrderEntity(int id, UserEntity userEntity) {
		this.id = id;
		this.userEntity = userEntity;
	}

	public OrderEntity(int id, UserEntity userEntity, String number, Set<OrderDetailEntity> orderDetailEntities) {
		this.id = id;
		this.userEntity = userEntity;
		this.number = number;
		this.orderDetailEntities = orderDetailEntities;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id", nullable = false)
	public UserEntity getUserEntity() {
		return this.userEntity;
	}

	public void setUserEntity(UserEntity userEntity) {
		this.userEntity = userEntity;
	}

	@Column(name = "number", length = 100)
	public String getNumber() {
		return this.number;
	}

	public void setNumber(String number) {
		this.number = number;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "orderEntity")
	public Set<OrderDetailEntity> getOrderDetailEntities() {
		return this.orderDetailEntities;
	}

	public void setOrderDetailEntities(Set<OrderDetailEntity> orderDetailEntities) {
		this.orderDetailEntities = orderDetailEntities;
	}

}
