package eg.com.otloblana.service.entity;

// Generated Nov 9, 2015 12:01:04 AM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * SizeEntity generated by hbm2java
 */
@Entity
@Table(name = "size")
public class SizeEntity implements java.io.Serializable {

	private int id;
	private String nameAr;
	private String nameEn;
	private Set<OrderDetailEntity> orderDetailEntities = new HashSet<OrderDetailEntity>(0);

	public SizeEntity() {
	}

	public SizeEntity(int id, String nameAr, String nameEn) {
		this.id = id;
		this.nameAr = nameAr;
		this.nameEn = nameEn;
	}

	public SizeEntity(int id, String nameAr, String nameEn,
					  Set<OrderDetailEntity> orderDetailEntities) {
		this.id = id;
		this.nameAr = nameAr;
		this.nameEn = nameEn;
		this.orderDetailEntities = orderDetailEntities;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "name_ar", nullable = false, length = 45)
	public String getNameAr() {
		return this.nameAr;
	}

	public void setNameAr(String nameAr) {
		this.nameAr = nameAr;
	}

	@Column(name = "name_en", nullable = false, length = 45)
	public String getNameEn() {
		return this.nameEn;
	}

	public void setNameEn(String nameEn) {
		this.nameEn = nameEn;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sizeEntity")
	public Set<OrderDetailEntity> getOrderDetailEntities() {
		return this.orderDetailEntities;
	}

	public void setOrderDetailEntities(Set<OrderDetailEntity> orderDetailEntities) {
		this.orderDetailEntities = orderDetailEntities;
	}

}
