package eg.com.otloblana.service.entity;

// Generated Nov 9, 2015 12:01:04 AM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * UserEntity generated by hbm2java
 */
@Entity
@Table(name = "user")
public class UserEntity implements java.io.Serializable {

	private int id;
	private String name;
	private String email;
	private String username;
	private String password;
	private String mobile;
	private String fbAccessToken;
	private byte[] img;
	private Set<GroupEntity> groupEntities = new HashSet<GroupEntity>(0);
	private Set<MemberEntity> memberEntities = new HashSet<MemberEntity>(0);
	private Set<OrderEntity> orderEntities = new HashSet<OrderEntity>(0);

	public UserEntity() {
	}

	public UserEntity(int id, String name) {
		this.id = id;
		this.name = name;
	}

	public UserEntity(int id, String name, String email, String username,
					  String password, String mobile, String fbAccessToken, byte[] img,
					  Set<GroupEntity> groupEntities, Set<MemberEntity> memberEntities, Set<OrderEntity> orderEntities) {
		this.id = id;
		this.name = name;
		this.email = email;
		this.username = username;
		this.password = password;
		this.mobile = mobile;
		this.fbAccessToken = fbAccessToken;
		this.img = img;
		this.groupEntities = groupEntities;
		this.memberEntities = memberEntities;
		this.orderEntities = orderEntities;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false, length = 200)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "email", length = 45)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "username", length = 50)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "password", length = 50)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "mobile", length = 45)
	public String getMobile() {
		return this.mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	@Column(name = "fb_access_token", length = 100)
	public String getFbAccessToken() {
		return this.fbAccessToken;
	}

	public void setFbAccessToken(String fbAccessToken) {
		this.fbAccessToken = fbAccessToken;
	}

	@Column(name = "img")
	public byte[] getImg() {
		return this.img;
	}

	public void setImg(byte[] img) {
		this.img = img;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userEntity")
	public Set<GroupEntity> getGroupEntities() {
		return this.groupEntities;
	}

	public void setGroupEntities(Set<GroupEntity> groupEntities) {
		this.groupEntities = groupEntities;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userEntity")
	public Set<MemberEntity> getMemberEntities() {
		return this.memberEntities;
	}

	public void setMemberEntities(Set<MemberEntity> memberEntities) {
		this.memberEntities = memberEntities;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userEntity")
	public Set<OrderEntity> getOrderEntities() {
		return this.orderEntities;
	}

	public void setOrderEntities(Set<OrderEntity> orderEntities) {
		this.orderEntities = orderEntities;
	}

}
