package eg.com.otloblana.model.entity;

// Generated Nov 9, 2015 12:01:04 AM by Hibernate Tools 4.0.0

import eg.com.otloblana.common.entity.GenericEntity;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * CategoryEntity generated by hbm2java
 */
@Entity
@Table(name = "category")
public class CategoryEntity implements java.io.Serializable,GenericEntity {

	private int id;
	private String nameAr;
	private String nameEn;
	private Set<ProductEntity> productEntities = new HashSet<ProductEntity>(0);

	public CategoryEntity() {
	}

	public CategoryEntity(int id, String nameAr, String nameEn) {
		this.id = id;
		this.nameAr = nameAr;
		this.nameEn = nameEn;
	}

	public CategoryEntity(int id, String nameAr, String nameEn, Set<ProductEntity> productEntities) {
		this.id = id;
		this.nameAr = nameAr;
		this.nameEn = nameEn;
		this.productEntities = productEntities;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "name_ar", nullable = false, length = 100)
	public String getNameAr() {
		return this.nameAr;
	}

	public void setNameAr(String nameAr) {
		this.nameAr = nameAr;
	}

	@Column(name = "name_en", nullable = false, length = 100)
	public String getNameEn() {
		return this.nameEn;
	}

	public void setNameEn(String nameEn) {
		this.nameEn = nameEn;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "categoryEntity")
	public Set<ProductEntity> getProductEntities() {
		return this.productEntities;
	}

	public void setProductEntities(Set<ProductEntity> productEntities) {
		this.productEntities = productEntities;
	}

}
