package eg.com.otloblana.model.entity;

// Generated Nov 9, 2015 12:01:04 AM by Hibernate Tools 4.0.0

import eg.com.otloblana.common.entity.GenericEntity;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * MemberEntity generated by hbm2java
 */
@Entity
@Table(name = "member", uniqueConstraints = @UniqueConstraint(columnNames = {
		"group_id", "user_id" }))
public class MemberEntity implements java.io.Serializable,GenericEntity {

	private int id;
	private UserEntity userEntity;
	private GroupEntity groupEntity;
	private boolean isAdmin;

	public MemberEntity() {
	}

	public MemberEntity(int id, UserEntity userEntity, GroupEntity groupEntity, boolean isAdmin) {
		this.id = id;
		this.userEntity = userEntity;
		this.groupEntity = groupEntity;
		this.isAdmin = isAdmin;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id", nullable = false)
	public UserEntity getUserEntity() {
		return this.userEntity;
	}

	public void setUserEntity(UserEntity userEntity) {
		this.userEntity = userEntity;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "group_id", nullable = false)
	public GroupEntity getGroupEntity() {
		return this.groupEntity;
	}

	public void setGroupEntity(GroupEntity groupEntity) {
		this.groupEntity = groupEntity;
	}

	@Column(name = "isAdmin", nullable = false)
	public boolean isIsAdmin() {
		return this.isAdmin;
	}

	public void setIsAdmin(boolean isAdmin) {
		this.isAdmin = isAdmin;
	}

}
