package eg.com.otloblana.model.entity;

// Generated Nov 9, 2015 12:01:04 AM by Hibernate Tools 4.0.0

import eg.com.otloblana.common.entity.GenericEntity;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * OrderDetailEntity generated by hbm2java
 */
@Entity
@Table(name = "order_detail")
public class OrderDetailEntity implements java.io.Serializable,GenericEntity {

	private int id;
	private AddonEntity addonEntity;
	private OrderEntity orderEntity;
	private SizeEntity sizeEntity;
	private ProductEntity productEntity;
	private int qty;

	public OrderDetailEntity() {
	}

	public OrderDetailEntity(int id, OrderEntity orderEntity, SizeEntity sizeEntity, ProductEntity productEntity, int qty) {
		this.id = id;
		this.orderEntity = orderEntity;
		this.sizeEntity = sizeEntity;
		this.productEntity = productEntity;
		this.qty = qty;
	}

	public OrderDetailEntity(int id, AddonEntity addonEntity, OrderEntity orderEntity, SizeEntity sizeEntity,
							 ProductEntity productEntity, int qty) {
		this.id = id;
		this.addonEntity = addonEntity;
		this.orderEntity = orderEntity;
		this.sizeEntity = sizeEntity;
		this.productEntity = productEntity;
		this.qty = qty;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "addon_id")
	public AddonEntity getAddonEntity() {
		return this.addonEntity;
	}

	public void setAddonEntity(AddonEntity addonEntity) {
		this.addonEntity = addonEntity;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "order_id", nullable = false)
	public OrderEntity getOrderEntity() {
		return this.orderEntity;
	}

	public void setOrderEntity(OrderEntity orderEntity) {
		this.orderEntity = orderEntity;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "size_id", nullable = false)
	public SizeEntity getSizeEntity() {
		return this.sizeEntity;
	}

	public void setSizeEntity(SizeEntity sizeEntity) {
		this.sizeEntity = sizeEntity;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "product_id", nullable = false)
	public ProductEntity getProductEntity() {
		return this.productEntity;
	}

	public void setProductEntity(ProductEntity productEntity) {
		this.productEntity = productEntity;
	}

	@Column(name = "qty", nullable = false)
	public int getQty() {
		return this.qty;
	}

	public void setQty(int qty) {
		this.qty = qty;
	}

}
