package eg.com.otloblana.model.entity;

// Generated Nov 9, 2015 12:01:04 AM by Hibernate Tools 4.0.0

import eg.com.otloblana.common.entity.GenericEntity;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * PriceListEntity generated by hbm2java
 */
@Entity
@Table(name = "price_list", uniqueConstraints = @UniqueConstraint(columnNames = {
		"product_id", "store_id" }))
public class PriceListEntity implements java.io.Serializable,GenericEntity {

	private int id;
	private StoreEntity storeEntity;
	private ProductEntity productEntity;
	private float price;

	public PriceListEntity() {
	}

	public PriceListEntity(int id, StoreEntity storeEntity, ProductEntity productEntity, float price) {
		this.id = id;
		this.storeEntity = storeEntity;
		this.productEntity = productEntity;
		this.price = price;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "store_id", nullable = false)
	public StoreEntity getStoreEntity() {
		return this.storeEntity;
	}

	public void setStoreEntity(StoreEntity storeEntity) {
		this.storeEntity = storeEntity;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "product_id", nullable = false)
	public ProductEntity getProductEntity() {
		return this.productEntity;
	}

	public void setProductEntity(ProductEntity productEntity) {
		this.productEntity = productEntity;
	}

	@Column(name = "price", nullable = false, precision = 12, scale = 0)
	public float getPrice() {
		return this.price;
	}

	public void setPrice(float price) {
		this.price = price;
	}

}
