package eg.com.otloblana.model.entity;

// Generated Nov 9, 2015 12:01:04 AM by Hibernate Tools 4.0.0

import eg.com.otloblana.common.entity.GenericEntity;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ProductEntity generated by hbm2java
 */
@Entity
@Table(name = "product")
public class ProductEntity implements java.io.Serializable,GenericEntity {

	private int id;
	private CategoryEntity categoryEntity;
	private String name;
	private Set<PriceListEntity> priceListEntities = new HashSet<PriceListEntity>(0);
	private Set<OrderDetailEntity> orderDetailEntities = new HashSet<OrderDetailEntity>(0);

	public ProductEntity() {
	}

	public ProductEntity(int id, CategoryEntity categoryEntity, String name) {
		this.id = id;
		this.categoryEntity = categoryEntity;
		this.name = name;
	}

	public ProductEntity(int id, CategoryEntity categoryEntity, String name,
						 Set<PriceListEntity> priceListEntities, Set<OrderDetailEntity> orderDetailEntities) {
		this.id = id;
		this.categoryEntity = categoryEntity;
		this.name = name;
		this.priceListEntities = priceListEntities;
		this.orderDetailEntities = orderDetailEntities;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "category_id", nullable = false)
	public CategoryEntity getCategoryEntity() {
		return this.categoryEntity;
	}

	public void setCategoryEntity(CategoryEntity categoryEntity) {
		this.categoryEntity = categoryEntity;
	}

	@Column(name = "name", nullable = false, length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "productEntity")
	public Set<PriceListEntity> getPriceListEntities() {
		return this.priceListEntities;
	}

	public void setPriceListEntities(Set<PriceListEntity> priceListEntities) {
		this.priceListEntities = priceListEntities;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "productEntity")
	public Set<OrderDetailEntity> getOrderDetailEntities() {
		return this.orderDetailEntities;
	}

	public void setOrderDetailEntities(Set<OrderDetailEntity> orderDetailEntities) {
		this.orderDetailEntities = orderDetailEntities;
	}

}
