package eg.com.otloblana.model.dto;

// Generated Nov 9, 2015 9:29:03 PM by Hibernate Tools 4.0.0

import com.fasterxml.jackson.annotation.JsonIgnore;
import eg.com.otloblana.common.dto.GenericDto;

import javax.enterprise.inject.Produces;
import java.util.ArrayList;
import java.util.List;

/**
 * CategoryDto generated by hbm2java
 */
public class CategoryDto implements java.io.Serializable,GenericDto {

	private int id;
	private String nameAr;
	private String nameEn;
	@JsonIgnore
	private List<ProductDto> productDtos = new ArrayList<ProductDto>(0);

	public CategoryDto() {
	}

	public CategoryDto(int id, String nameAr, String nameEn) {
		this.id = id;
		this.nameAr = nameAr;
		this.nameEn = nameEn;
	}

	public CategoryDto(int id, String nameAr, String nameEn, List<ProductDto> productDtos) {
		this.id = id;
		this.nameAr = nameAr;
		this.nameEn = nameEn;
		this.productDtos = productDtos;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getNameAr() {
		return this.nameAr;
	}

	public void setNameAr(String nameAr) {
		this.nameAr = nameAr;
	}

	public String getNameEn() {
		return this.nameEn;
	}

	public void setNameEn(String nameEn) {
		this.nameEn = nameEn;
	}

	public List getProductDtos() {
		return this.productDtos;
	}

	public void setProductDtos(List productDtos) {
		this.productDtos = productDtos;
	}

}
