package eg.com.otloblana.model.dto;

// Generated Nov 9, 2015 9:29:03 PM by Hibernate Tools 4.0.0

import eg.com.otloblana.common.dto.GenericDto;

import javax.persistence.Column;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Set;

/**
 * OrderDto generated by hbm2java
 */
public class OrderDto implements java.io.Serializable,GenericDto {

	private int id;
	private UserDto userDto;
	private String number;
	private Date createTime;
	private Date timeToOrder;
	private boolean isDelivered;
	private boolean isOrdered;
	private boolean isDraft;

	private List<OrderDetailDto> orderDetailDtos = new ArrayList<OrderDetailDto>(0);

	public OrderDto() {
	}

	public OrderDto(int id, UserDto userDto) {
		this.id = id;
		this.userDto = userDto;
	}

	public OrderDto(int id, UserDto userDto, String number, List<OrderDetailDto> orderDetailDtos) {
		this.id = id;
		this.userDto = userDto;
		this.number = number;
		this.orderDetailDtos = orderDetailDtos;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public UserDto getUserDto() {
		return this.userDto;
	}

	public void setUserDto(UserDto userDto) {
		this.userDto = userDto;
	}

	public String getNumber() {
		return this.number;
	}

	public void setNumber(String number) {
		this.number = number;
	}

	public List getOrderDetailDtos() {
		return this.orderDetailDtos;
	}

	public void setOrderDetailDtos(List orderDetailDtos) {
		this.orderDetailDtos = orderDetailDtos;
	}


	public Date getCreateTime() {
		return createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}


	public Date getTimeToOrder() {
		return timeToOrder;
	}

	public void setTimeToOrder(Date timeToOrder) {
		this.timeToOrder = timeToOrder;
	}


	public boolean getIsDelivered() {
		return isDelivered;
	}

	public void setIsDelivered(boolean isDelivered) {
		this.isDelivered = isDelivered;
	}


	public boolean getIsOrdered() {
		return isOrdered;
	}

	public void setIsOrdered(boolean isOrdered) {
		this.isOrdered = isOrdered;
	}


	public boolean getIsDraft() {
		return isDraft;
	}

	public void setIsDraft(boolean isDraft) {
		this.isDraft = isDraft;
	}
}
