package eg.com.otloblana.model.dto;

// Generated Nov 9, 2015 9:29:03 PM by Hibernate Tools 4.0.0

import com.fasterxml.jackson.annotation.JsonIgnore;
import eg.com.otloblana.common.dto.GenericDto;

/**
 * OrderDetailDto generated by hbm2java
 */
public class OrderDetailDto implements java.io.Serializable,GenericDto {

	private int id;
	private AddonDto addonDto;

	@JsonIgnore
	private OrderDto orderDto;

	private SizeDto sizeDto;
	private ProductDto productDto;
	private int qty;

	public OrderDetailDto() {
	}

	public OrderDetailDto(int id, OrderDto orderDto, SizeDto sizeDto, ProductDto productDto, int qty) {
		this.id = id;
		this.orderDto = orderDto;
		this.sizeDto = sizeDto;
		this.productDto = productDto;
		this.qty = qty;
	}

	public OrderDetailDto(int id, AddonDto addonDto, OrderDto orderDto, SizeDto sizeDto,
						  ProductDto productDto, int qty) {
		this.id = id;
		this.addonDto = addonDto;
		this.orderDto = orderDto;
		this.sizeDto = sizeDto;
		this.productDto = productDto;
		this.qty = qty;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public AddonDto getAddonDto() {
		return this.addonDto;
	}

	public void setAddonDto(AddonDto addonDto) {
		this.addonDto = addonDto;
	}

	public OrderDto getOrderDto() {
		return this.orderDto;
	}

	public void setOrderDto(OrderDto orderDto) {
		this.orderDto = orderDto;
	}

	public SizeDto getSizeDto() {
		return this.sizeDto;
	}

	public void setSizeDto(SizeDto sizeDto) {
		this.sizeDto = sizeDto;
	}

	public ProductDto getProductDto() {
		return this.productDto;
	}

	public void setProductDto(ProductDto productDto) {
		this.productDto = productDto;
	}

	public int getQty() {
		return this.qty;
	}

	public void setQty(int qty) {
		this.qty = qty;
	}

}
