package eg.com.otloblana.model.dto;

// Generated Nov 9, 2015 9:29:03 PM by Hibernate Tools 4.0.0

import eg.com.otloblana.common.dto.GenericDto;

import java.util.HashSet;
import java.util.Set;

/**
 * ProductDto generated by hbm2java
 */
public class ProductDto implements java.io.Serializable,GenericDto {

	private int id;
	private CategoryDto categoryDto;
	private String name;
	private Set priceListDtos = new HashSet(0);
	private Set orderDetailDtos = new HashSet(0);

	public ProductDto() {
	}

	public ProductDto(int id, CategoryDto categoryDto, String name) {
		this.id = id;
		this.categoryDto = categoryDto;
		this.name = name;
	}

	public ProductDto(int id, CategoryDto categoryDto, String name, Set priceListDtos,
					  Set orderDetailDtos) {
		this.id = id;
		this.categoryDto = categoryDto;
		this.name = name;
		this.priceListDtos = priceListDtos;
		this.orderDetailDtos = orderDetailDtos;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public CategoryDto getCategoryDto() {
		return this.categoryDto;
	}

	public void setCategoryDto(CategoryDto categoryDto) {
		this.categoryDto = categoryDto;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Set getPriceListDtos() {
		return this.priceListDtos;
	}

	public void setPriceListDtos(Set priceListDtos) {
		this.priceListDtos = priceListDtos;
	}

	public Set getOrderDetailDtos() {
		return this.orderDetailDtos;
	}

	public void setOrderDetailDtos(Set orderDetailDtos) {
		this.orderDetailDtos = orderDetailDtos;
	}

}
