package eg.com.otloblana.model.dto;

// Generated Nov 9, 2015 9:29:03 PM by Hibernate Tools 4.0.0

import com.fasterxml.jackson.annotation.JsonIgnore;
import eg.com.otloblana.common.dto.GenericDto;

import java.util.ArrayList;
import java.util.List;
import java.util.Set;

/**
 * ProductDto generated by hbm2java
 */
public class ProductDto implements java.io.Serializable,GenericDto {

	private int id;
	private CategoryDto categoryDto;
	private String name;
	@JsonIgnore
	private List<PriceListDto> priceListDtos = new ArrayList<PriceListDto>(0);
	@JsonIgnore
	private List<OrderDetailDto> orderDetailDtos = new ArrayList<OrderDetailDto>(0);

	public ProductDto() {
	}

	public ProductDto(int id, CategoryDto categoryDto, String name) {
		this.id = id;
		this.categoryDto = categoryDto;
		this.name = name;
	}

	public ProductDto(int id, CategoryDto categoryDto, String name, List<PriceListDto> priceListDtos,
					  List<OrderDetailDto> orderDetailDtos) {
		this.id = id;
		this.categoryDto = categoryDto;
		this.name = name;
		this.priceListDtos = priceListDtos;
		this.orderDetailDtos = orderDetailDtos;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public CategoryDto getCategoryDto() {
		return this.categoryDto;
	}

	public void setCategoryDto(CategoryDto categoryDto) {
		this.categoryDto = categoryDto;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public List getPriceListDtos() {
		return this.priceListDtos;
	}

	public void setPriceListDtos(List<PriceListDto> priceListDtos) {
		this.priceListDtos = priceListDtos;
	}

	public List getOrderDetailDtos() {
		return this.orderDetailDtos;
	}

	public void setOrderDetailDtos(List<OrderDetailDto> orderDetailDtos) {
		this.orderDetailDtos = orderDetailDtos;
	}

}
