package eg.com.otloblana.service.dto;

// Generated Nov 9, 2015 9:29:03 PM by Hibernate Tools 4.0.0

import eg.com.otloblana.common.dto.GenericDto;

/**
 * MemberDto generated by hbm2java
 */
public class MemberDto implements java.io.Serializable,GenericDto {

	private int id;
	private UserDto userDto;
	private GroupDto groupDto;
	private boolean isAdmin;

	public MemberDto() {
	}

	public MemberDto(int id, UserDto userDto, GroupDto groupDto, boolean isAdmin) {
		this.id = id;
		this.userDto = userDto;
		this.groupDto = groupDto;
		this.isAdmin = isAdmin;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public UserDto getUserDto() {
		return this.userDto;
	}

	public void setUserDto(UserDto userDto) {
		this.userDto = userDto;
	}

	public GroupDto getGroupDto() {
		return this.groupDto;
	}

	public void setGroupDto(GroupDto groupDto) {
		this.groupDto = groupDto;
	}

	public boolean isIsAdmin() {
		return this.isAdmin;
	}

	public void setIsAdmin(boolean isAdmin) {
		this.isAdmin = isAdmin;
	}

}
