package eg.com.otloblana.service.dto;

// Generated Nov 9, 2015 9:29:03 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * OrderDto generated by hbm2java
 */
public class OrderDto implements java.io.Serializable {

	private int id;
	private UserDto userDto;
	private String number;
	private Set orderDetails = new HashSet(0);

	public OrderDto() {
	}

	public OrderDto(int id, UserDto userDto) {
		this.id = id;
		this.userDto = userDto;
	}

	public OrderDto(int id, UserDto userDto, String number, Set orderDetails) {
		this.id = id;
		this.userDto = userDto;
		this.number = number;
		this.orderDetails = orderDetails;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public UserDto getUserDto() {
		return this.userDto;
	}

	public void setUserDto(UserDto userDto) {
		this.userDto = userDto;
	}

	public String getNumber() {
		return this.number;
	}

	public void setNumber(String number) {
		this.number = number;
	}

	public Set getOrderDetails() {
		return this.orderDetails;
	}

	public void setOrderDetails(Set orderDetails) {
		this.orderDetails = orderDetails;
	}

}
