package eg.com.otloblana.service.dto;

// Generated Nov 9, 2015 9:29:03 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * ProductDto generated by hbm2java
 */
public class ProductDto implements java.io.Serializable {

	private int id;
	private CategoryDto categoryDto;
	private String name;
	private Set priceLists = new HashSet(0);
	private Set orderDetails = new HashSet(0);

	public ProductDto() {
	}

	public ProductDto(int id, CategoryDto categoryDto, String name) {
		this.id = id;
		this.categoryDto = categoryDto;
		this.name = name;
	}

	public ProductDto(int id, CategoryDto categoryDto, String name, Set priceLists,
					  Set orderDetails) {
		this.id = id;
		this.categoryDto = categoryDto;
		this.name = name;
		this.priceLists = priceLists;
		this.orderDetails = orderDetails;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public CategoryDto getCategoryDto() {
		return this.categoryDto;
	}

	public void setCategoryDto(CategoryDto categoryDto) {
		this.categoryDto = categoryDto;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Set getPriceLists() {
		return this.priceLists;
	}

	public void setPriceLists(Set priceLists) {
		this.priceLists = priceLists;
	}

	public Set getOrderDetails() {
		return this.orderDetails;
	}

	public void setOrderDetails(Set orderDetails) {
		this.orderDetails = orderDetails;
	}

}
