package eg.com.otloblana.service.dto;

// Generated Nov 9, 2015 9:29:03 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * SizeDto generated by hbm2java
 */
public class SizeDto implements java.io.Serializable {

	private int id;
	private String nameAr;
	private String nameEn;
	private Set orderDetails = new HashSet(0);

	public SizeDto() {
	}

	public SizeDto(int id, String nameAr, String nameEn) {
		this.id = id;
		this.nameAr = nameAr;
		this.nameEn = nameEn;
	}

	public SizeDto(int id, String nameAr, String nameEn, Set orderDetails) {
		this.id = id;
		this.nameAr = nameAr;
		this.nameEn = nameEn;
		this.orderDetails = orderDetails;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getNameAr() {
		return this.nameAr;
	}

	public void setNameAr(String nameAr) {
		this.nameAr = nameAr;
	}

	public String getNameEn() {
		return this.nameEn;
	}

	public void setNameEn(String nameEn) {
		this.nameEn = nameEn;
	}

	public Set getOrderDetails() {
		return this.orderDetails;
	}

	public void setOrderDetails(Set orderDetails) {
		this.orderDetails = orderDetails;
	}

}
