package eg.com.otloblana.service.dto;

// Generated Nov 9, 2015 9:29:03 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * StoreDto generated by hbm2java
 */
public class StoreDto implements java.io.Serializable {

	private int id;
	private String name;
	private Set priceLists = new HashSet(0);

	public StoreDto() {
	}

	public StoreDto(int id, String name) {
		this.id = id;
		this.name = name;
	}

	public StoreDto(int id, String name, Set priceLists) {
		this.id = id;
		this.name = name;
		this.priceLists = priceLists;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Set getPriceLists() {
		return this.priceLists;
	}

	public void setPriceLists(Set priceLists) {
		this.priceLists = priceLists;
	}

}
