package eg.com.otloblana.service.dto;

// Generated Nov 9, 2015 9:29:03 PM by Hibernate Tools 4.0.0

import eg.com.otloblana.common.dto.GenericDto;

import java.util.HashSet;
import java.util.Set;

/**
 * UserDto generated by hbm2java
 */
public class UserDto implements java.io.Serializable,GenericDto {

	private int id;
	private String name;
	private String email;
	private String username;
	private String password;
	private String mobile;
	private String fbAccessToken;
	private byte[] img;
	private Set groupDtos = new HashSet(0);
	private Set memberDtos = new HashSet(0);
	private Set orderDtos = new HashSet(0);

	public UserDto() {
	}

	public UserDto(int id, String name) {
		this.id = id;
		this.name = name;
	}

	public UserDto(int id, String name, String email, String username,
				   String password, String mobile, String fbAccessToken, byte[] img,
				   Set groupDtos, Set memberDtos, Set orderDtos) {
		this.id = id;
		this.name = name;
		this.email = email;
		this.username = username;
		this.password = password;
		this.mobile = mobile;
		this.fbAccessToken = fbAccessToken;
		this.img = img;
		this.groupDtos = groupDtos;
		this.memberDtos = memberDtos;
		this.orderDtos = orderDtos;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getMobile() {
		return this.mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	public String getFbAccessToken() {
		return this.fbAccessToken;
	}

	public void setFbAccessToken(String fbAccessToken) {
		this.fbAccessToken = fbAccessToken;
	}

	public byte[] getImg() {
		return this.img;
	}

	public void setImg(byte[] img) {
		this.img = img;
	}

	public Set getGroupDtos() {
		return this.groupDtos;
	}

	public void setGroupDtos(Set groupDtos) {
		this.groupDtos = groupDtos;
	}

	public Set getMemberDtos() {
		return this.memberDtos;
	}

	public void setMemberDtos(Set memberDtos) {
		this.memberDtos = memberDtos;
	}

	public Set getOrderDtos() {
		return this.orderDtos;
	}

	public void setOrderDtos(Set orderDtos) {
		this.orderDtos = orderDtos;
	}

}
